In [4]:
import numpy as np
import pandas as pd

train = pd.read_csv("train.csv")

In [7]:
train.head(1)

id             titulo  \
0  254099  depto. tipo a-402   

                                         descripcion tipodepropiedad  \
0  depto. interior de 80.15m2, consta de sala com...     Apartamento   

                         direccion         ciudad         provincia  \
0  Avenida Division del Norte 2005  Benito Juárez  Distrito Federal   

   antiguedad  habitaciones  garages  ...   idzona  lat  lng  \
0         NaN           2.0      1.0  ...  23533.0  NaN  NaN   

                 fecha  gimnasio  usosmultiples piscina  escuelascercanas  \
0  2015-08-23 00:00:00       0.0            0.0     0.0               0.0   

   centroscomercialescercanos     precio  
0                         0.0  2273000.0  

[1 rows x 23 columns]

In [18]:
##### Entendiendo como usar KNN #####


from sklearn.neighbors import NearestNeighbors

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])

nbrs = NearestNeighbors(n_neighbors=3, algorithm='ball_tree').fit(X)

distances, indices = nbrs.kneighbors(X)

In [19]:
indices

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0],
       [3, 4, 5],
       [4, 3, 5],
       [5, 4, 3]])

In [20]:
distances

array([[0.        , 1.        , 2.23606798],
       [0.        , 1.        , 1.41421356],
       [0.        , 1.41421356, 2.23606798],
       [0.        , 1.        , 2.23606798],
       [0.        , 1.        , 1.41421356],
       [0.        , 1.41421356, 2.23606798]])

In [21]:
nbrs.kneighbors_graph(X).toarray()

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])